/**
 * Home page - Landing page with system introduction, metrics, and disclaimers.
 */

import { useState, useEffect } from 'react';
import { Link } from 'react-router-dom';
import { api } from '../services/api';
import type { PublicMetricsResponse } from '../types';
import './HomePage.css';

export function HomePage() {
  const [metrics, setMetrics] = useState<PublicMetricsResponse | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    loadMetrics();
  }, []);

  const loadMetrics = async () => {
    setLoading(true);
    try {
      const data = await api.getPublicMetrics();
      setMetrics(data);
    } catch (err) {
      console.error('Failed to load metrics:', err);
      setMetrics({ claim_count: 0, blog_count: 0, question_count: 0 });
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="home-page">
      <div className="home-container">
        {/* Hero Section */}
        <section className="hero-section">
          <h1>TheReceipts</h1>
          <p className="tagline">Forensic Claim Analysis for Christianity</p>
          <p className="description">
            A transparent, multi-agent verification system that audits Christian apologetics claims
            through rigorous source checking and adversarial review. We audit claims, not beliefs.
          </p>
        </section>

        {/* How It Works */}
        <section className="how-it-works">
          <h2>How It Works</h2>
          <p className="section-intro">
            Every claim runs through a 5-agent verification pipeline: Topic Finder, Source Checker,
            Adversarial Checker, Writing Agent, and Publisher. No shortcuts, no hedging.
          </p>
          <div className="system-grid">
            <div className="system-card">
              <h3>
                <Link to="/ask">Ask</Link>
              </h3>
              <p>
                Ask any question about Christian apologetics claims. Get fast answers from our
                pre-audited claim library, or trigger a full verification pipeline for novel claims.
              </p>
            </div>
            <div className="system-card">
              <h3>
                <Link to="/read">Read</Link>
              </h3>
              <p>
                Browse synthesized articles covering complex apologetics topics. Each article
                combines multiple verified claim cards into accessible, long-form analysis.
              </p>
            </div>
            <div className="system-card">
              <h3>
                <Link to="/audits">Audits</Link>
              </h3>
              <p>
                Explore the full repository of audited claim cards. Filter by category, verdict,
                or search for specific topics. Every card shows transparent sources and verification.
              </p>
            </div>
          </div>
        </section>

        {/* Live Metrics */}
        <section className="metrics-section">
          <h2>Live Metrics</h2>
          {loading ? (
            <div className="metrics-loading">
              <div className="spinner"></div>
              <p>Loading metrics...</p>
            </div>
          ) : (
            <div className="metrics-grid">
              <div className="metric-card">
                <div className="metric-value">{metrics?.claim_count.toLocaleString()}</div>
                <div className="metric-label">Audited Claims</div>
              </div>
              <div className="metric-card">
                <div className="metric-value">{metrics?.blog_count.toLocaleString()}</div>
                <div className="metric-label">Blog Articles</div>
              </div>
              <div className="metric-card">
                <div className="metric-value">{metrics?.question_count.toLocaleString()}</div>
                <div className="metric-label">Questions Answered</div>
              </div>
            </div>
          )}
        </section>

        {/* AI Disclaimer */}
        <section className="disclaimer-section">
          <h2>AI-Generated Content Disclaimer</h2>
          <div className="disclaimer-box">
            <p>
              All content on this platform is generated by Large Language Models (LLMs) as part of
              a multi-agent verification pipeline. While we use source verification and adversarial
              checking to improve accuracy, AI-generated content can contain errors, hallucinations,
              or misinterpretations.
            </p>
            <p>
              <strong>You should independently verify any claims before relying on them.</strong> This
              platform is designed as a research and educational tool, not as a definitive source of
              truth. Always consult primary sources and peer-reviewed scholarship directly.
            </p>
          </div>
        </section>

        {/* TOS Placeholder */}
        <section className="tos-section">
          <h2>Terms of Service</h2>
          <div className="tos-box">
            <p>
              This platform is provided for educational and research purposes. By using this service,
              you agree to:
            </p>
            <ul>
              <li>Verify information independently before relying on it</li>
              <li>Use the platform responsibly and within its intended scope</li>
              <li>Not use the service to harass, harm, or deceive others</li>
              <li>Respect copyright and intellectual property rights of cited sources</li>
            </ul>
            <p>
              <strong>Abuse Policy:</strong> Attempts to spam, manipulate, or abuse the system
              (including prompt injection or adversarial inputs) may result in access restrictions.
            </p>
            <p className="tos-footer">
              Terms subject to change.
            </p>
          </div>
        </section>
      </div>
    </div>
  );
}
