"""Initial schema: claim_cards, sources, apologetics_tags, agent_prompts, topic_queue

Revision ID: 597a35a22323
Revises:
Create Date: 2026-01-12 23:05:44.364787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = '597a35a22323'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_prompts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_name', sa.String(length=100), nullable=False),
    sa.Column('llm_provider', sa.String(length=50), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('max_tokens', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_name')
    )
    op.create_index('ix_agent_prompts_agent_name', 'agent_prompts', ['agent_name'], unique=False)
    op.create_table('claim_cards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('claim_text', sa.Text(), nullable=False),
    sa.Column('claimant', sa.String(length=500), nullable=False),
    sa.Column('claim_type', sa.String(length=100), nullable=True),
    sa.Column('verdict', sa.Enum('TRUE', 'MISLEADING', 'FALSE', 'UNFALSIFIABLE', 'DEPENDS_ON_DEFINITIONS', name='verdictenum'), nullable=False),
    sa.Column('short_answer', sa.Text(), nullable=False),
    sa.Column('deep_answer', sa.Text(), nullable=False),
    sa.Column('why_persists', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence_level', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='confidencelevelenum'), nullable=False),
    sa.Column('confidence_explanation', sa.Text(), nullable=False),
    sa.Column('agent_audit', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('embedding', Vector(1536), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_claim_cards_claim_text', 'claim_cards', ['claim_text'], unique=False)
    op.create_index('ix_claim_cards_claimant', 'claim_cards', ['claimant'], unique=False)
    op.create_index('ix_claim_cards_created_at', 'claim_cards', ['created_at'], unique=False)
    op.create_index('ix_claim_cards_verdict', 'claim_cards', ['verdict'], unique=False)
    op.create_table('topic_queue',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('topic_text', sa.Text(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'PROCESSING', 'COMPLETED', 'FAILED', name='topicstatusenum'), nullable=False),
    sa.Column('source', sa.String(length=500), nullable=True),
    sa.Column('claim_card_ids', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('scheduled_for', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_topic_queue_priority', 'topic_queue', ['priority'], unique=False)
    op.create_index('ix_topic_queue_scheduled_for', 'topic_queue', ['scheduled_for'], unique=False)
    op.create_index('ix_topic_queue_status', 'topic_queue', ['status'], unique=False)
    op.create_table('apologetics_tags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('claim_card_id', sa.UUID(), nullable=False),
    sa.Column('technique_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['claim_card_id'], ['claim_cards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_apologetics_tags_claim_card_id', 'apologetics_tags', ['claim_card_id'], unique=False)
    op.create_index('ix_apologetics_tags_technique_name', 'apologetics_tags', ['technique_name'], unique=False)
    op.create_table('sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('claim_card_id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.Enum('PRIMARY_HISTORICAL', 'SCHOLARLY_PEER_REVIEWED', name='sourcetypeenum'), nullable=False),
    sa.Column('citation', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('quote_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['claim_card_id'], ['claim_cards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sources_claim_card_id', 'sources', ['claim_card_id'], unique=False)
    op.create_index('ix_sources_source_type', 'sources', ['source_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sources_source_type', table_name='sources')
    op.drop_index('ix_sources_claim_card_id', table_name='sources')
    op.drop_table('sources')
    op.drop_index('ix_apologetics_tags_technique_name', table_name='apologetics_tags')
    op.drop_index('ix_apologetics_tags_claim_card_id', table_name='apologetics_tags')
    op.drop_table('apologetics_tags')
    op.drop_index('ix_topic_queue_status', table_name='topic_queue')
    op.drop_index('ix_topic_queue_scheduled_for', table_name='topic_queue')
    op.drop_index('ix_topic_queue_priority', table_name='topic_queue')
    op.drop_table('topic_queue')
    op.drop_index('ix_claim_cards_verdict', table_name='claim_cards')
    op.drop_index('ix_claim_cards_created_at', table_name='claim_cards')
    op.drop_index('ix_claim_cards_claimant', table_name='claim_cards')
    op.drop_index('ix_claim_cards_claim_text', table_name='claim_cards')
    op.drop_table('claim_cards')
    op.drop_index('ix_agent_prompts_agent_name', table_name='agent_prompts')
    op.drop_table('agent_prompts')
    # ### end Alembic commands ###
