"""Add category_tags table

Revision ID: d2c6d3c1f6dc
Revises: 597a35a22323
Create Date: 2026-01-12 23:36:46.747565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2c6d3c1f6dc'
down_revision: Union[str, None] = '597a35a22323'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category_tags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('claim_card_id', sa.UUID(), nullable=False),
    sa.Column('category_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['claim_card_id'], ['claim_cards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_category_tags_category_name', 'category_tags', ['category_name'], unique=False)
    op.create_index('ix_category_tags_claim_card_id', 'category_tags', ['claim_card_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_category_tags_claim_card_id', table_name='category_tags')
    op.drop_index('ix_category_tags_category_name', table_name='category_tags')
    op.drop_table('category_tags')
    # ### end Alembic commands ###
