"""add_usage_context_to_sources

Revision ID: f01c3b619027
Revises: d2c6d3c1f6dc
Create Date: 2026-01-13 19:33:03.615989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f01c3b619027'
down_revision: Union[str, None] = 'd2c6d3c1f6dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sources', sa.Column('usage_context', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sources', 'usage_context')
    # ### end Alembic commands ###
